#ifndef PAL_NDS_CONFIG_H
#define PAL_NDS_CONFIG_H

#define PAL_HAS_JOYSTICKS 0
#define PAL_HAS_TOUCH 0

#define PAL_DEFAULT_WINDOW_WIDTH 256
#define PAL_DEFAULT_WINDOW_HEIGHT 192
#define PAL_DEFAULT_FULLSCREEN_HEIGHT 192
#define PAL_DEFAULT_TEXTURE_WIDTH 256
#define PAL_DEFAULT_TEXTURE_HEIGHT 192

#define PAL_PREFIX "nitro:/"
#define PAL_SAVE_PREFIX "fat:/"
#define PAL_CONFIG_PREFIX PAL_SAVE_PREFIX

#define PAL_VIDEO_INIT_FLAGS SDL_WINDOW_SHOWN
#define PAL_SDL_INIT_FLAGS (SDL_INIT_VIDEO | SDL_INIT_NOPARACHUTE)

#define PAL_PLATFORM "Nintendo DS"
#define PAL_CREDIT NULL
#define PAL_PORTYEAR NULL

#define PAL_HAS_CONFIG_PAGE 0
#define PAL_HAS_NATIVEMIDI 0
#define PAL_HAS_MP3 0
#define PAL_HAS_OGG 0
#define PAL_HAS_OPUS 0
#define PAL_HAS_GLSL 0

#define PAL_FATAL_OUTPUT(s)

#include <sys/time.h>

#endif
