#!/usr/bin/env python3
#
# SDLPAL
# Copyright (c) 2011-2026, SDLPAL development team.
# All rights reserved.
#
# This file is part of SDLPAL.
#
# SDLPAL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SDLPAL is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
"""Generate the fixed-rate read-only tables for the embedded MAME OPL2 core.

The formulas intentionally mirror adplug/mame/fmopl.cpp.h version 0.72.
Generation happens on the host so the embedded build carries neither the
mutable 40 KiB table set nor the libm initialization path.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


OPL_CLOCK = 3_579_545
SAMPLE_RATE = 22_050
ENV_STEP = 128.0 / 1024.0
TL_RES_LEN = 256
TL_LEVELS = 12
TL_TAB_LEN = TL_LEVELS * 2 * TL_RES_LEN
SIN_LEN = 1024
FREQ_SH = 16
EG_SH = 16
LFO_SH = 24
KSL_TABLE = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 12, 16, 20, 24, 28, 32,
    0, 0, 0, 0, 0, 12, 20, 28, 32, 40, 44, 48, 52, 56, 60, 64,
    0, 0, 0, 20, 32, 44, 52, 60, 64, 72, 76, 80, 84, 88, 92, 96,
    0, 0, 32, 52, 64, 76, 84, 92, 96, 104, 108, 112, 116, 120, 124, 128,
    0, 32, 64, 84, 96, 108, 116, 124, 128, 136, 140, 144, 148, 152, 156, 160,
    0, 64, 96, 116, 128, 140, 148, 156, 160, 168, 172, 176, 180, 184, 188, 192,
    0, 96, 128, 148, 160, 172, 180, 188, 192, 200, 204, 208, 212, 216, 220, 224,
]


def build_tl_table() -> list[int]:
    table = [0] * TL_TAB_LEN
    for x in range(TL_RES_LEN):
        magnitude = math.floor(
            (1 << 16) / math.pow(2.0, (x + 1) * (ENV_STEP / 4.0) / 8.0)
        )
        value = int(magnitude) >> 4
        value = (value >> 1) + (1 if value & 1 else 0)
        value <<= 1
        table[x * 2] = value
        table[x * 2 + 1] = -value
        for level in range(1, TL_LEVELS):
            shifted = value >> level
            offset = x * 2 + level * 2 * TL_RES_LEN
            table[offset] = shifted
            table[offset + 1] = -shifted
    assert min(table) >= -32768 and max(table) <= 32767
    return table


def build_sin_table() -> list[int]:
    table = [0] * (SIN_LEN * 4)
    for i in range(SIN_LEN):
        sample = math.sin(((i * 2) + 1) * math.pi / SIN_LEN)
        attenuation = 8.0 * math.log(1.0 / abs(sample)) / math.log(2.0)
        attenuation /= ENV_STEP / 4.0
        value = int(2.0 * attenuation)
        value = (value >> 1) + (1 if value & 1 else 0)
        table[i] = value * 2 + (0 if sample >= 0.0 else 1)

    for i in range(SIN_LEN):
        table[SIN_LEN + i] = TL_TAB_LEN if i & (1 << 9) else table[i]
        table[2 * SIN_LEN + i] = table[i & 0x1FF]
        table[3 * SIN_LEN + i] = (
            TL_TAB_LEN if i & (1 << 8) else table[i & 0xFF]
        )
    assert min(table) >= 0 and max(table) <= 65535
    return table


def build_fn_table() -> list[int]:
    freqbase = (float(OPL_CLOCK) / 72.0) / float(SAMPLE_RATE)
    return [
        int(float(i) * 64.0 * freqbase * float(1 << (FREQ_SH - 10)))
        for i in range(1024)
    ]


def fixed_scalars() -> dict[str, int]:
    freqbase = (float(OPL_CLOCK) / 72.0) / float(SAMPLE_RATE)
    return {
        "PAL_MAME_OPL2_FIXED_LFO_AM_INC": int(
            (1.0 / 64.0) * float(1 << LFO_SH) * freqbase
        ),
        "PAL_MAME_OPL2_FIXED_LFO_PM_INC": int(
            (1.0 / 1024.0) * float(1 << LFO_SH) * freqbase
        ),
        "PAL_MAME_OPL2_FIXED_NOISE_F": int(float(1 << FREQ_SH) * freqbase),
        "PAL_MAME_OPL2_FIXED_EG_TIMER_ADD": int(
            float(1 << EG_SH) * freqbase
        ),
        "PAL_MAME_OPL2_FIXED_EG_TIMER_OVERFLOW": 1 << EG_SH,
    }


def format_array(
    ctype: str,
    name: str,
    values: list[int],
    values_per_line: int,
) -> str:
    lines = [
        f"static const {ctype} {name}[{len(values)}] "
        "PAL_MAME_OPL2_FIXED_RODATA = {"
    ]
    for start in range(0, len(values), values_per_line):
        row = values[start : start + values_per_line]
        lines.append("    " + ", ".join(str(value) for value in row) + ",")
    lines.append("};")
    return "\n".join(lines)


def generate() -> str:
    scalars = fixed_scalars()
    pieces = [
        "/* Generated by tools/pal_mame_opl2_tables.py; do not edit. */",
        "/*",
        " * Derived from MAME FMOPL v0.72 by Jarek Burczynski and",
        " * Tatsuyuki Satoh (GPL-2.0-or-later), as adapted by SDLPAL.",
        " * YM3812 3579545 Hz -> 22050 Hz.",
        " */",
        "#ifndef PAL_MAME_OPL2_FIXED_TABLES_INC",
        "#define PAL_MAME_OPL2_FIXED_TABLES_INC",
        "",
        "#if defined(__GNUC__)",
        "#define PAL_MAME_OPL2_FIXED_RODATA \\",
        '    __attribute__((section(".rodata.pal_mame_opl2"), aligned(4)))',
        "#else",
        "#define PAL_MAME_OPL2_FIXED_RODATA",
        "#endif",
        "",
        f"#define PAL_MAME_OPL2_FIXED_CLOCK {OPL_CLOCK}u",
        f"#define PAL_MAME_OPL2_FIXED_RATE {SAMPLE_RATE}u",
    ]
    pieces.extend(f"#define {name} {value}u" for name, value in scalars.items())
    pieces.extend(
        [
            "",
            format_array(
                "int16_t",
                "pal_mame_opl2_fixed_tl_tab",
                build_tl_table(),
                16,
            ),
            "",
            format_array(
                "uint16_t",
                "pal_mame_opl2_fixed_sin_tab",
                build_sin_table(),
                16,
            ),
            "",
            format_array(
                "uint32_t",
                "pal_mame_opl2_fixed_fn_tab",
                build_fn_table(),
                8,
            ),
            "",
            format_array(
                "uint16_t",
                "pal_mame_opl2_fixed_ksl_tab",
                KSL_TABLE,
                16,
            ),
            "",
            "#undef PAL_MAME_OPL2_FIXED_RODATA",
            "#endif",
            "",
        ]
    )
    return "\n".join(pieces)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("embedded/pal_mame_opl2_fixed_tables.inc"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output does not already equal regenerated content",
    )
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not args.output.is_file() or args.output.read_text() != content:
            print(f"stale generated OPL2 tables: {args.output}")
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
