idf_component_register(
    SRCS
        "app_main.c"
        "cores3se_board.c"
        "cores3se_memory.c"
        "pal_save_fatfs.c"
        "../../embedded/pal_dialog_static.c"
        "../../embedded/pal_font_cache.c"
        "../../embedded/pal_global_cache.c"
        "../../embedded/pal_pack.c"
        "../../embedded/pal_palette_static.c"
        "../../embedded/pal_scene_cache.c"
        "../../embedded/pal_text_cache.c"
        "../../embedded/pal_ui_cache.c"
        "../../embedded/pal_video_static.c"
    INCLUDE_DIRS
        "."
        "../../embedded"
    REQUIRES
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_sdspi
        esp_driver_spi
        esp_lcd
        esp_partition
        fatfs
        sdmmc
)

target_compile_definitions(${COMPONENT_LIB} PRIVATE
    PAL_ESP_CORES3SE=1
    PAL_SCENE_ENABLE_PINNED=1
)
